### Request with authentication
GET http://localhost:8080/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAwMzgzOCwiaWF0IjoxNzUwMDAwMjM4LCJzY29wZSI6IlJPTEVfVVNFUiJ9.rUhjVHtNopyUhaBIdE2IeCi4-c5EmkgryuW90LatS75ssLOzix5IZbz_qEDlcEVKhk14NtXXEIPNEbeJdsXVVIlfft0rsQyyi36M5w7L9_lT6RdnyS3AcWbp2z1tMzClKvq8dZCuD4-eOz1iQdAdepUQasic2gC-6o6IrOrzQd6PbAc36g3p3cugfOkeFU71xj9fGNfz0F-sGGW4kafC8u1y1TCIy3_42pyVUDXFOpdT0WBZa0LqanyRSuNaBn6YfA_kyBtgAYHKcuNE8RoLWmkx5q5gScqmg7peqk1aIi57pzazLYuObpkpjrdlQAuFzcFPPrZ4amAub-G9bWdVlQ

{
}


### Request Profile
GET http://localhost:8080/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAwMzgzOCwiaWF0IjoxNzUwMDAwMjM4LCJzY29wZSI6IlJPTEVfVVNFUiJ9.rUhjVHtNopyUhaBIdE2IeCi4-c5EmkgryuW90LatS75ssLOzix5IZbz_qEDlcEVKhk14NtXXEIPNEbeJdsXVVIlfft0rsQyyi36M5w7L9_lT6RdnyS3AcWbp2z1tMzClKvq8dZCuD4-eOz1iQdAdepUQasic2gC-6o6IrOrzQd6PbAc36g3p3cugfOkeFU71xj9fGNfz0F-sGGW4kafC8u1y1TCIy3_42pyVUDXFOpdT0WBZa0LqanyRSuNaBn6YfA_kyBtgAYHKcuNE8RoLWmkx5q5gScqmg7peqk1aIi57pzazLYuObpkpjrdlQAuFzcFPPrZ4amAub-G9bWdVlQ

{
}



### LOGOUT
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAwMzgzOCwiaWF0IjoxNzUwMDAwMjM4LCJzY29wZSI6IlJPTEVfVVNFUiJ9.rUhjVHtNopyUhaBIdE2IeCi4-c5EmkgryuW90LatS75ssLOzix5IZbz_qEDlcEVKhk14NtXXEIPNEbeJdsXVVIlfft0rsQyyi36M5w7L9_lT6RdnyS3AcWbp2z1tMzClKvq8dZCuD4-eOz1iQdAdepUQasic2gC-6o6IrOrzQd6PbAc36g3p3cugfOkeFU71xj9fGNfz0F-sGGW4kafC8u1y1TCIy3_42pyVUDXFOpdT0WBZa0LqanyRSuNaBn6YfA_kyBtgAYHKcuNE8RoLWmkx5q5gScqmg7peqk1aIi57pzazLYuObpkpjrdlQAuFzcFPPrZ4amAub-G9bWdVlQ

{
}



### BASIC AUTH
POST localhost:8080/token
Authorization: Basic YWxleDpwYXNzd29yZA==


### POST LOGIN
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "alex",
  "password": "azerty123"
}