### Request with authentication
GET http://localhost:8080/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAxNDUzMCwiaWF0IjoxNzUwMDEwOTMwLCJzY29wZSI6IlJPTEVfVVNFUiJ9.PbpttwlSvcsRx2H5me5mXx0noooU7JaOoBoqOnhuPSE0s2J1eJ1WUlsun3rWYEiMiYgc0UlpPbVCd04mZZHMEYoEerF0OPG7aG-watsg9Vyy-pi3V0Rw3NaUElsrzFWvzf8t9Eh82lf1bL0L2zsBilgI4CAYq5xkBNwy5KCB36fYEpBSQR8Vr4d7wz5kXlr-fW_OdHqV21fToBIGixeg0n_JgWSXO7Y5LT7-_bgaITGaOuG-O6K56H04NpbllLy_fi1TQOx-yNEMt5CJsaHP20xpX1LvKsAVRphnVvVmRQZ6SOfJtXY8Lt_jOSKcM5kRqGmJ5k_fPsZ_jkhfz1BAzQ
//Authorization: Bearer

{
}

### LOGOUT
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAxNDUzMCwiaWF0IjoxNzUwMDEwOTMwLCJzY29wZSI6IlJPTEVfVVNFUiJ9.PbpttwlSvcsRx2H5me5mXx0noooU7JaOoBoqOnhuPSE0s2J1eJ1WUlsun3rWYEiMiYgc0UlpPbVCd04mZZHMEYoEerF0OPG7aG-watsg9Vyy-pi3V0Rw3NaUElsrzFWvzf8t9Eh82lf1bL0L2zsBilgI4CAYq5xkBNwy5KCB36fYEpBSQR8Vr4d7wz5kXlr-fW_OdHqV21fToBIGixeg0n_JgWSXO7Y5LT7-_bgaITGaOuG-O6K56H04NpbllLy_fi1TQOx-yNEMt5CJsaHP20xpX1LvKsAVRphnVvVmRQZ6SOfJtXY8Lt_jOSKcM5kRqGmJ5k_fPsZ_jkhfz1BAzQ

{
}


### Request Profile
GET http://localhost:8080/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAwNzU3NiwiaWF0IjoxNzUwMDAzOTc2LCJzY29wZSI6IlJPTEVfVVNFUiJ9.ebEe42xiAcgTfNrMP3uy85dtod8zhM2S4XQ8ahBVOXz3PGOL49Mqc7OheDC0mVdyQxUx1aRjIoutIWdk70YPhxrNQtBUi2Ven919iX8H6i1SlVa8cqjwDQiZpA7Er35L4cWwCHd8AkxFMw460VI_6UWmQNX9LT3Udsk-zWuKPAytNKbT3QxxjsmTICjjgaOLzRNnL_Ha0UERBpIknWNREafPm9a0wDmxv_fIhqAiwJIY3IvUfwL2c1kimZZ4qcOt8_SPRFi_89Pkv82oeVnI2tkS0N7WEh-WGp9E5ZCQACz81lhvouu1C6T9DTDEg28hJRA6k5RqavWEf-QHQRvkyg

{
}






### POST LOGIN
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "alex",
  "password": "azerty123"
}