### Request with authentication
GET http://localhost:8080/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAxMDMwMiwiaWF0IjoxNzUwMDA2NzAyLCJzY29wZSI6IlJPTEVfVVNFUiJ9.ffbVRZga7cSZ9jqDurWLfPsjarvNVg4lY5gb5Lar5Qp07tY5wTdKW1NKEEsno-dgqtt5nOYEUSGCVidfVV0oEl6S05RhNGAY9g6kJXBtGXQqYgvbEVZYCfl5x4a2yccpyecM-8Ei6n_ovQ2RYw2oeVFSwot4krhCvoKZH3KE8aMhjn2vTcnkHhGOTFvfyiVhgpd4aiPRzzg57De1UQD74XEd-jX1jW4wZY1hKACyQ7FVbdbqO3xG2JF_4W6KT_TJGlnq8h0TZDqFHm2qQL2Brcd43dX2tvlhW5QNznXpOhpluJY3lnpCM0i-U93Dr0_W8McggK0k2ydWkW9j7wsEeA

{
}


### Request Profile
GET http://localhost:8080/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAwNzU3NiwiaWF0IjoxNzUwMDAzOTc2LCJzY29wZSI6IlJPTEVfVVNFUiJ9.ebEe42xiAcgTfNrMP3uy85dtod8zhM2S4XQ8ahBVOXz3PGOL49Mqc7OheDC0mVdyQxUx1aRjIoutIWdk70YPhxrNQtBUi2Ven919iX8H6i1SlVa8cqjwDQiZpA7Er35L4cWwCHd8AkxFMw460VI_6UWmQNX9LT3Udsk-zWuKPAytNKbT3QxxjsmTICjjgaOLzRNnL_Ha0UERBpIknWNREafPm9a0wDmxv_fIhqAiwJIY3IvUfwL2c1kimZZ4qcOt8_SPRFi_89Pkv82oeVnI2tkS0N7WEh-WGp9E5ZCQACz81lhvouu1C6T9DTDEg28hJRA6k5RqavWEf-QHQRvkyg

{
}



### LOGOUT
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWxleCIsImV4cCI6MTc1MDAxMDMwMiwiaWF0IjoxNzUwMDA2NzAyLCJzY29wZSI6IlJPTEVfVVNFUiJ9.ffbVRZga7cSZ9jqDurWLfPsjarvNVg4lY5gb5Lar5Qp07tY5wTdKW1NKEEsno-dgqtt5nOYEUSGCVidfVV0oEl6S05RhNGAY9g6kJXBtGXQqYgvbEVZYCfl5x4a2yccpyecM-8Ei6n_ovQ2RYw2oeVFSwot4krhCvoKZH3KE8aMhjn2vTcnkHhGOTFvfyiVhgpd4aiPRzzg57De1UQD74XEd-jX1jW4wZY1hKACyQ7FVbdbqO3xG2JF_4W6KT_TJGlnq8h0TZDqFHm2qQL2Brcd43dX2tvlhW5QNznXpOhpluJY3lnpCM0i-U93Dr0_W8McggK0k2ydWkW9j7wsEeA

{
}


### POST LOGIN
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "alex",
  "password": "azerty123"
}